FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["src/CommentService/CommentService.Api/CommentService.Api.csproj", "src/CommentService/CommentService.Api/"]
COPY ["src/CommentService/CommentService.Application/CommentService.Application.csproj", "src/CommentService/CommentService.Application/"]
COPY ["src/CommentService/CommentService.Domain/CommentService.Domain.csproj", "src/CommentService/CommentService.Domain/"]
COPY ["src/CommentService/CommentService.Infrastructure/CommentService.Infrastructure.csproj", "src/CommentService/CommentService.Infrastructure/"]
COPY ["src/Shared/HappyHeadlines.Observability/HappyHeadlines.Observability.csproj", "src/Shared/HappyHeadlines.Observability/"]

RUN dotnet restore "src/CommentService/CommentService.Api/CommentService.Api.csproj"

COPY . .

WORKDIR "/src/src/CommentService/CommentService.Api"
RUN dotnet build "CommentService.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "CommentService.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CommentService.Api.dll"]