events {
    worker_connections 1024;
}

http {

    upstream article_api {
        server article-api-1:8080;
        server article-api-2:8080;
        server article-api-3:8080;
    }

    upstream draft_api {
        server draft-api-1:8080;
        server draft-api-2:8080;
        server draft-api-3:8080;
    }

    upstream comment_api {
        server comment-api-1:8080;
        server comment-api-2:8080;
        server comment-api-3:8080;
    }

    server {
        listen 80;

        location /api/articles {
            proxy_pass         http://article_api;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /api/comments {
            proxy_pass         http://comment_api;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /api/drafts {
            proxy_pass         http://draft_api;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}